### ISSUE TITLE
Add expand()

### ISSUE THREAD

**Issue by tuminzee** [vkruglikov/react-telegram-web-app#21]
Addition of expand() which is a method that expands the Web App to the maximum available height.

Do you plan to work on this?

So that this could be plugged in as the default behaviour for the user when the interact with the TWA

**Comment by vkruglikov** [comment]
@tuminzee , Hi! Thank you for issue.
Yes, sure, I am adding `expand` on next version!

**Comment by vkruglikov** [comment]
If you need to use it right now, you can use WebApp API directly

**Comment by tuminzee** [comment]
Thank you @vkruglikov

**Comment by rexydye** [comment]
By the way, what is the release date of the new version?

**Comment by vkruglikov** [comment]
https://github.com/vkruglikov/react-telegram-web-app/pull/26

@rexydye  @tuminzee 

Added useExpand hook in 1.11.0
Thank you

**Comment by tuminzee** [comment]
Thank you so much for this @vkruglikov 
I will test it out LGTM!
more power 🔥 🕺🏼
