### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by umidullo** [vkruglikov/react-telegram-web-app#38]
can you add a general hook (useWebApp for example) to get properties from window.Telegram.WebApp?
e.g platform, enableClosingConfirmation(), disableClosingConfirmation() etc...

**Comment by vkruglikov** [comment]
Hi. Thank you for report . Yes, I think it will be good idea. 

Hook useWebApp already have in core hooks, so need just check interface and publish to public.

I am going to add it to the next release

**Comment by vkruglikov** [comment]
https://github.com/vkruglikov/react-telegram-web-app/pull/39

**Comment by vkruglikov** [comment]
release https://github.com/vkruglikov/react-telegram-web-app/pull/40

**Comment by vkruglikov** [comment]
The hook `useWebApp` was added, but it has an `unknown` type. It is temporary and will be changed in the future
