### ISSUE TITLE
disabled MainButton still has normal appearance

### ISSUE THREAD

**Issue by dannylin108** [vkruglikov/react-telegram-web-app#44]
Package version: 2.1.4
React version: "^18.2.0"

## Steps To Reproduce

1. Render `<MainButton disabled text='Update' onClick={()=> update()} />`

## The current behavior

Button still looks like active, but doesn't accept clicks.

## The expected behavior

Button expected to look "disabled" (somehow grayed out, etc).

**Comment by vkruglikov** [comment]
@dannylin108  
Hi! Thank you for issue report.

When you pass `disabled` prop to `MainButton` component, this package just calls a `WebApp.MainButton.disable()` method in `react` context. 

The package doesn't change the color of the MainButton, I think Telegram should do it.
If you pass `disabled` to `MainButton`, you can see that `onClick` doesn't call.

Try to use [this demo of MiniApp](https://t.me/react_telegram_web_app_bot/demo ). There is `disable` input  for `MainButton` 

 
Based on the tests passed all work correctly. 

I think I can't help with this issue

**Comment by dannylin108** [comment]
Ok, I see. So it's Telegram's part is not implemented correctly. 

I just saw in recently published Telegram's @wallet bot, the main button becomes grey when disabled. So they probably change the color manually.

**Comment by vkruglikov** [comment]
Yes, I think they change it manually.

You can pass [`color` ](https://github.com/vkruglikov/react-telegram-web-app/blob/master/docs/interfaces/MainButtonProps.md#color) to `MainButton` component
