### ISSUE TITLE
Mainbutton and Backbutton not show in next.js

### ISSUE THREAD

**Issue by pursonchen** [vkruglikov/react-telegram-web-app#46]
Package version: 2.1.4
React version: 18.2.0
Telegram.WebApp version: 

## Steps To Reproduce

1. create a next.js app
2. pnpm add @vkruglikov/react-telegram-web-app
3. add Privoder and Mainbutton in app/page.tsx
```typescript
"use client"
import {
  BackButton,
  MainButton,
  WebAppProvider,
} from "@vkruglikov/react-telegram-web-app";

export default function Page() {
  return (
    <WebAppProvider
      options={{
        smoothButtonsTransition: true,
      }}
    >
      <h1>Hello, Quest Page!</h1>
      <MainButton text="Continue with task" progress={true} />       
      <BackButton onClick={() => console.log("back")} />
    </WebAppProvider>
  );
}

```
4. run `pnpm dev && ngrok 3000`
5. update the webapp bot URL to ngrok provide
6. click the bot URL and see the result. 
![image](https://github.com/vkruglikov/react-telegram-web-app/assets/17820243/d1fca72b-23b9-4038-942e-75b22113fcba)

Link to code example:

**Comment by vkruglikov** [comment]
Hi, Are there any errors in console?

Did you add `telegram-web-app.js` script in the page ?

https://core.telegram.org/bots/webapps#initializing-mini-apps

**Comment by pursonchen** [comment]
> @pursonchen Hi, Are there any errors in console?
> 
> Did you add `telegram-web-app.js` script in the page ?
> 
> https://core.telegram.org/bots/webapps#initializing-mini-apps

Thank you for your reply.

Thera are not any errors in the console. Here are the screenshots inspecting my web app:

<img width="1447" alt="image" src="https://github.com/vkruglikov/react-telegram-web-app/assets/17820243/67047325-9401-4fe6-8b0b-27eb08859263">

<img width="1394" alt="image" src="https://github.com/vkruglikov/react-telegram-web-app/assets/17820243/c9928917-9f98-47e6-a0a5-660b510b2fae">

**Comment by vkruglikov** [comment]
@pursonchen  I have not found a problem with the package.
I have created app by ```npx create-next-app@latest```,
and did basic setup steps 

Try to place telegram-web-app.js in the Head  src/pages/_document.tsx

```
<Head>
    <script src="https://telegram.org/js/telegram-web-app.js" />
</Head>
```

**Comment by pursonchen** [comment]
> @pursonchen I have not found a problem with the package. I have created app by `npx create-next-app@latest`, and did basic setup steps
> 
> Try to place telegram-web-app.js in the Head src/pages/_document.tsx
> 
> ```
> <Head>
>     <script src="https://telegram.org/js/telegram-web-app.js" />
> </Head>
> ```

Thank you for trying. I used the `app router` style. I've not tried the ` pages router` style.
Would you like to try it on the `app router ` style?

FYI:https://nextjs.org/docs/app

**Comment by pursonchen** [comment]
> @pursonchen I have not found a problem with the package. I have created app by `npx create-next-app@latest`, and did basic setup steps
> 
> Try to place telegram-web-app.js in the Head src/pages/_document.tsx
> 
> ```
> <Head>
>     <script src="https://telegram.org/js/telegram-web-app.js" />
> </Head>
> ```

Great , If I change my project from app router to pages router, it works good. thank you. Maybe I'm not good understand the new version nextjs with app router.

**Comment by vkruglikov** [comment]
@pursonchen Hello! I have tried to create nextjs app with App Router.
Have not found any problem

<img width="200" alt="Снимок экрана 2023-10-27 в 22 39 28" src="https://github.com/vkruglikov/react-telegram-web-app/assets/9719024/0c8ba201-3f19-4a62-beef-9b3c18af4fb0">


Bellow important steps to reproduce.

Create app by:

<img width="500" alt="Снимок экрана 2023-10-27 в 22 47 58" src="https://github.com/vkruglikov/react-telegram-web-app/assets/9719024/03ca56b5-9414-4e77-8ad4-22ed3451d3ec">

`package.json`
```json
  "@vkruglikov/react-telegram-web-app": "^2.1.4",
  "next": "14.0.0",
```

`src/app/layout.tsx`
```jsx
<html lang="en">
    <head>
        <script src="https://telegram.org/js/telegram-web-app.js" />
    </head>
    <body className={inter.className}>{children}</body>
</html>
```

`src/app/page.tsx`
```jsx
'use client';

import Image from 'next/image'
import styles from './page.module.css'
import { WebAppProvider, MainButton, BackButton } from '@vkruglikov/react-telegram-web-app';

<main className={styles.main}>
    <WebAppProvider
        options={{
            smoothButtonsTransition: true,
        }}
    >
        <MainButton  />
        <BackButton  />
    </WebAppProvider>
</main>
```

**Comment by pursonchen** [comment]
> @pursonchen Hello! I have tried to create nextjs app with App Router. Have not found any problem
> 
> <img alt="Снимок экрана 2023-10-27 в 22 39 28" width="200" src="https://user-images.githubusercontent.com/9719024/278691993-0c8ba201-3f19-4a62-beef-9b3c18af4fb0.png">
> Bellow important steps to reproduce.
> 
> Create app by:
> 
> <img alt="Снимок экрана 2023-10-27 в 22 47 58" width="500" src="https://user-images.githubusercontent.com/9719024/278694072-03ca56b5-9414-4e77-8ad4-22ed3451d3ec.png">
> `package.json`
> 
> ```json
>   "@vkruglikov/react-telegram-web-app": "^2.1.4",
>   "next": "14.0.0",
> ```
> 
> `src/app/layout.tsx`
> 
> ```js
> <html lang="en">
>     <head>
>         <script src="https://telegram.org/js/telegram-web-app.js" />
>     </head>
>     <body className={inter.className}>{children}</body>
> </html>
> ```
> 
> `src/app/page.tsx`
> 
> ```js
> 'use client';
> 
> import Image from 'next/image'
> import styles from './page.module.css'
> import { WebAppProvider, MainButton, BackButton } from '@vkruglikov/react-telegram-web-app';
> 
> <main className={styles.main}>
>     <WebAppProvider
>         options={{
>             smoothButtonsTransition: true,
>         }}
>     >
>         <MainButton  />
>         <BackButton  />
>     </WebAppProvider>
> </main>
> ```

Thank you again, it’s so weird , later I will try again. 
Here I got another question, The script can’t load because of cors. I made the web app url https://a.com, but the script’s url is from https://telegram.org. Could you give me an advise.☺️

**Comment by guilledev01** [comment]
Hi,
It seems to be a nextjs bug when using <Script>

[see bug here](https://github.com/vercel/next.js/issues/57931)

**Comment by necropreneur** [comment]
> @pursonchen Hello! I have tried to create nextjs app with App Router. Have not found any problem
> 
> <img alt="Снимок экрана 2023-10-27 в 22 39 28" width="200" src="https://private-user-images.githubusercontent.com/9719024/278691993-0c8ba201-3f19-4a62-beef-9b3c18af4fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTI1MzksIm5iZiI6MTcxMzg5MjIzOSwicGF0aCI6Ii85NzE5MDI0LzI3ODY5MTk5My0wYzhiYTIwMS0zZjE5LTRhNjItYmVlZi05YjNjMThhZjRmYjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTcxMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzgyZTZlNTA5YzhmYTA1MDY3ZWFiNWU2YzMwNjM4ZmMwNjMyYzA5NWIwOTg1ZDQyM2M3M2I3YmQ3MzE5Y2I3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y8spRLTASAMfH3rcA5tzvLD33SJ636YQixJlT-0ILBA">
> Bellow important steps to reproduce.
> 
> Create app by:
> 
> <img alt="Снимок экрана 2023-10-27 в 22 47 58" width="500" src="https://private-user-images.githubusercontent.com/9719024/278694072-03ca56b5-9414-4e77-8ad4-22ed3451d3ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4OTI1MzksIm5iZiI6MTcxMzg5MjIzOSwicGF0aCI6Ii85NzE5MDI0LzI3ODY5NDA3Mi0wM2NhNTZiNS05NDE0LTRlNzctOGFkNC0yMmVkMzQ1MWQzZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjNUMTcxMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDRhZDkwMTI2YjRlNTBmOTJiZjQwODMyYWYwMDVjZTAyZTY0YzQ0ZTYzYzI4YTIyOWYxNDVkY2EwZmQxOWRmMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9uxxeWd9s_oFpwHAV82ZbHNZUzFCI_c05yqx6SQSoDg">
> `package.json`
> 
> ```json
>   "@vkruglikov/react-telegram-web-app": "^2.1.4",
>   "next": "14.0.0",
> ```
> 
> `src/app/layout.tsx`
> 
> ```js
> <html lang="en">
>     <head>
>         <script src="https://telegram.org/js/telegram-web-app.js" />
>     </head>
>     <body className={inter.className}>{children}</body>
> </html>
> ```
> 
> `src/app/page.tsx`
> 
> ```js
> 'use client';
> 
> import Image from 'next/image'
> import styles from './page.module.css'
> import { WebAppProvider, MainButton, BackButton } from '@vkruglikov/react-telegram-web-app';
> 
> <main className={styles.main}>
>     <WebAppProvider
>         options={{
>             smoothButtonsTransition: true,
>         }}
>     >
>         <MainButton  />
>         <BackButton  />
>     </WebAppProvider>
> </main>
> ```

thank you sir! had issues using Script tag, this helped me a ton!
