### ISSUE TITLE
useInitData doesn't work with nextjs

### ISSUE THREAD

**Issue by alexgoto** [vkruglikov/react-telegram-web-app#52]
Exceptions throws when nextjs renders components on server and window.Telegram.WebApp is unavailable. 

Code does not handle this situation: 
https://github.com/vkruglikov/react-telegram-web-app/blob/7065c1573c22f0da056efffbbe7893cac3c9f17c/src/useInitData.ts#L60-L64

For example, this code (useShowPopup) works fine, because handles situation with temporarily unavailable window:
https://github.com/vkruglikov/react-telegram-web-app/blob/7065c1573c22f0da056efffbbe7893cac3c9f17c/src/useShowPopup.ts#L66-L82

I think we need do the same with useInitData. Or, simply, need to set undefined to initData and initDataUnsafe when window is unavailablle. 

I can make PR if you accept

**Comment by vkruglikov** [comment]
Hi @alexgoto !
Yes, of course, you are right. Need to use  optional chaining

If you create MR it will help the project

**Comment by un-hongly** [comment]
I have the same issue in nextjs.
