### ISSUE TITLE
WebAppUser.photo_url  has type "true", instead of "string"

### ISSUE THREAD

**Issue by alexgoto** [vkruglikov/react-telegram-web-app#56]
https://github.com/vkruglikov/react-telegram-web-app/blob/0d5125f7dbeb147cc177ad0511876caeed1107ce/src/core/twa-types/WebApp.d.ts#L59

In the docs:

![image](https://github.com/vkruglikov/react-telegram-web-app/assets/43707500/dfb2f4c3-c6e7-4bb7-869b-ad27e9a8bb96)

**Comment by vkruglikov** [comment]
@alexgoto Thank you, I will fix it. This is used for private methods only and doesn't affect public

**Comment by alexgoto** [comment]
@vkruglikov It is non-blocking problem. I noticed it accidentally and can make a PR in free time
